services: 
  db:
    image: mysql:latest
    ports:
      - 3306:3306
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD} 
      - MYSQL_ALLOW_EMPTY_PASSWORD=1 
    volumes:
      - "./db:/docker-entrypoint-initdb.d"
      - "mysqldata:/var/lib/mysql"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8001:80
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
volumes:
  mysqldata: